export const contactUsConstants = {
  heading: 'Contact Us',
  fullName: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  fullNameInvalidText: 'Full name is required.',
  email: 'Email',
  emailPlaceholder: 'Enter your E-mail id',
  emailInvalidText: 'Email is required.',
  phoneNumber: 'Phone Number',
  phoneNumberPlaceholder: '0999999999',
  phoneNumberInvalidText: 'Phone number is required.',
  message: 'Your Message',
  messageInvalidText: 'Message must be at least 10 characters long.',
  btnText: 'Send',
};
